from engines.base.types import EngineType, GameDefinition, RewardRule

MMO_EXPANSION_GAMES = [
    GameDefinition("anime_raid_akuma", "Akuma Anime Raid", "Co-op anime raid with boss phases, ultimates, shard drops, and ranked damage boards.", EngineType.BATTLE, "Anime Raid", 1, 6, 10, RewardRule(180, 130, 1.55, [{"item_id": "akuma_shard", "rarity": "epic", "weight": 8}]), {"variant_family": "anime_raids", "phases": 3}),
    GameDefinition("pirate_wars", "Pirate Wars", "Fleet strategy and raid hybrid with clans, treasure maps, ship cosmetics, and island control.", EngineType.STRATEGY, "Pirate Strategy", 2, 30, 25, RewardRule(220, 240, 1.35, [{"item_id": "kraken_map", "rarity": "legendary", "weight": 4}]), {"clan_war": True}),
    GameDefinition("zombie_horde_survival", "Zombie Horde Survival", "Endless horde mode with barricades, revives, elite mutations, and server survival records.", EngineType.BATTLE, "Horde Survival", 1, 5, 12, RewardRule(160, 115, 1.45, [{"item_id": "horde_trophy", "rarity": "rare", "weight": 12}]), {"endless": True}),
    GameDefinition("crystal_mining_rush", "Crystal Mining Rush", "Timed mining competition with boosters, ores, upgrades, and inflation-aware sinks.", EngineType.ECONOMY, "Mining", 1, 10, 5, RewardRule(85, 130, 1.3, [{"item_id": "prismatic_ore", "rarity": "epic", "weight": 7}]), {"competitive": True}),
    GameDefinition("ocean_fishing_cup", "Ocean Fishing Cup", "Fishing tournament with weather, rare fish, collectible aquariums, and weekly prizes.", EngineType.ECONOMY, "Fishing", 1, 20, 8, RewardRule(95, 100, 1.35, [{"item_id": "leviathan_scale", "rarity": "legendary", "weight": 3}]), {"tournament": True}),
    GameDefinition("reaction_arena_blitz", "Reaction Arena Blitz", "Mobile-first reaction arena with streak multipliers and viral leaderboard dethrones.", EngineType.REACTION, "Reaction", 2, 16, 3, RewardRule(60, 40, 1.8, []), {"mobile_first": True}),
    GameDefinition("memory_duel_prime", "Memory Duel Prime", "Head-to-head memory duel with ranked queues, spectators, and comeback mechanics.", EngineType.REACTION, "Memory", 2, 2, 4, RewardRule(70, 45, 1.7, []), {"ranked": True}),
    GameDefinition("tower_survival_omega", "Tower Survival Omega", "Tower survival with waves, boss lanes, tower cosmetics, and seasonal races.", EngineType.STRATEGY, "Tower Survival", 1, 4, 15, RewardRule(170, 130, 1.45, [{"item_id": "omega_tower_core", "rarity": "epic", "weight": 6}]), {"seasonal_race": True}),
    GameDefinition("card_battle_arcanum", "Card Battle Arcanum", "Card battle mode with deck rarity, combos, ranked seasons, and collection flexing.", EngineType.CARD, "Card Battle", 1, 2, 7, RewardRule(105, 80, 1.5, [{"item_id": "arcane_card_pack", "rarity": "rare", "weight": 15}]), {"deckbuilding": True}),
    GameDefinition("idle_empire_tycoon", "Idle Empire Tycoon", "Idle empire loop with resources, upgrades, clan boosts, and prestige races.", EngineType.STRATEGY, "Idle Empire", 1, 1, 2, RewardRule(75, 160, 1.2, []), {"idle": True, "prestige": True}),
]
