from engines.base.types import EngineType, GameDefinition, RewardRule

EXPANDED_GAMES = [
    GameDefinition(
        id="cosmic_fishing",
        name="Cosmic Fishing",
        description="Collection fishing with rarity catches, sell loops, weather events, and aquarium cosmetics.",
        engine_type=EngineType.ECONOMY,
        category="Collection",
        min_players=1,
        max_players=4,
        estimated_minutes=4,
        reward_rule=RewardRule(55, 65, 1.4, [{"item_id": "star_koi", "rarity": "rare", "weight": 12}]),
        config={"variants": ["nebula pond", "meteor pier"], "integrations": ["inventory", "leaderboards", "quests"]},
    ),
    GameDefinition(
        id="space_mining",
        name="Space Mining",
        description="Idle-click mining variant with ore upgrades, meteor modifiers, and economy sinks.",
        engine_type=EngineType.ECONOMY,
        category="Resource",
        min_players=1,
        max_players=6,
        estimated_minutes=5,
        reward_rule=RewardRule(70, 90, 1.35, [{"item_id": "lunar_ore", "rarity": "uncommon", "weight": 30}]),
        config={"upgrade_slots": ["drill", "scanner", "cargo"], "anti_abuse": {"click_cap_per_minute": 45}},
    ),
    GameDefinition(
        id="anime_duel",
        name="Anime Duel",
        description="Turn-based anime battle with rarity fighters, ultimates, ranked MMR, and cosmetics.",
        engine_type=EngineType.BATTLE,
        category="PvP Battle",
        min_players=1,
        max_players=2,
        estimated_minutes=6,
        reward_rule=RewardRule(110, 80, 1.55, [{"item_id": "hero_shard", "rarity": "rare", "weight": 18}]),
        config={"ranked": True, "abilities": ["Strike", "Counter", "Ultimate"]},
    ),
    GameDefinition(
        id="zombie_survival",
        name="Zombie Survival",
        description="Co-op wave survival with barricades, revives, elite zombies, and survival leaderboards.",
        engine_type=EngineType.BATTLE,
        category="Survival",
        min_players=1,
        max_players=5,
        estimated_minutes=10,
        reward_rule=RewardRule(130, 100, 1.5, [{"item_id": "survivor_badge", "rarity": "epic", "weight": 7}]),
        config={"waves": 12, "revives": True, "leaderboard_metric": "waves_survived"},
    ),
    GameDefinition(
        id="pirate_raid",
        name="Pirate Raid",
        description="Crew raid variant with treasure rooms, ship battles, curses, and clan contribution rewards.",
        engine_type=EngineType.BATTLE,
        category="Co-op Raid",
        min_players=1,
        max_players=6,
        estimated_minutes=9,
        reward_rule=RewardRule(125, 140, 1.45, [{"item_id": "captains_compass", "rarity": "legendary", "weight": 4}]),
        config={"clan_contribution": True, "rooms": ["deck", "hold", "captain cabin"]},
    ),
    GameDefinition(
        id="memory_rush",
        name="Memory Rush",
        description="Fast reaction-memory game with streak scoring, daily quests, and mobile-friendly buttons.",
        engine_type=EngineType.REACTION,
        category="Skill",
        min_players=1,
        max_players=8,
        estimated_minutes=3,
        reward_rule=RewardRule(45, 35, 1.8, []),
        config={"rounds": 7, "sequence_growth": True, "button_grid": "2x3"},
    ),
    GameDefinition(
        id="crystal_tower_defense",
        name="Crystal Tower Defense",
        description="Tower defense variant with waves, tower upgrades, survival rankings, and loot chests.",
        engine_type=EngineType.STRATEGY,
        category="Tower Defense",
        min_players=1,
        max_players=4,
        estimated_minutes=12,
        reward_rule=RewardRule(150, 115, 1.5, [{"item_id": "tower_core", "rarity": "epic", "weight": 8}]),
        config={"towers": ["arrow", "mage", "slow"], "waves": 20},
    ),
    GameDefinition(
        id="frostkeep_dungeon",
        name="Frostkeep Dungeon",
        description="Dungeon Raid variant using the shared raid systems with ice enemies and frost status effects.",
        engine_type=EngineType.BATTLE,
        category="Dungeon Variant",
        min_players=1,
        max_players=5,
        estimated_minutes=8,
        reward_rule=RewardRule(115, 85, 1.5, [{"item_id": "frost_rune", "rarity": "rare", "weight": 14}]),
        config={"variant_of": "dungeon_raid", "status_effect": "freeze"},
    ),
    GameDefinition(
        id="skyward_empire",
        name="Skyward Empire",
        description="Strategy variant with floating territories, alliances, resource caravans, and seasonal maps.",
        engine_type=EngineType.STRATEGY,
        category="Strategy Variant",
        min_players=2,
        max_players=40,
        estimated_minutes=25,
        reward_rule=RewardRule(210, 180, 1.35, []),
        config={"variant_of": "empire_conquest", "resource_nodes": ["aether", "ore", "food"]},
    ),
]
